In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [2]:
import numpy as np

In [3]:
A1=np.array([1,2,3,4])
print(A1)

[1 2 3 4]


In [4]:
type(A1)

numpy.ndarray

In [5]:
A1.shape

(4,)

In [6]:
A2=np.array([[1,2,3,4],[5,6,7,8]])
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
type(A2)

numpy.ndarray

In [8]:
A2.shape

(2, 4)

In [9]:
A2.size

8

In [10]:
A2.ndim

2

In [11]:
A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
type(A3)

numpy.ndarray

In [13]:
A3.shape

(1, 3, 3)

In [14]:
A3.size


9

In [15]:
A3.ndim


3

In [16]:
import numpy as np
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [17]:
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [18]:
z1.shape

(3,)

In [22]:
z1.ndim

1

In [23]:
type(z1)


numpy.ndarray

In [24]:
z2=np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
type(z2)

numpy.ndarray

In [27]:
z2.shape

(3, 4)

In [28]:
z2.size

12

In [29]:
z2.ndim

2

In [30]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [31]:
z3=np.zeros((2,3,4),dtype=int)
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [32]:
type(z3)

numpy.ndarray

In [33]:
z3.ndim

3

In [34]:
z3.size

24

In [35]:
z3.shape

(2, 3, 4)

In [36]:
import numpy as np
a1=np.ones(3)
a1

array([1., 1., 1.])

In [37]:
a1=np.ones(3,dtype=int)
a1

array([1, 1, 1])

In [38]:
type(a1)

numpy.ndarray

In [39]:
a1.ndim

1

In [40]:
a1.shape

(3,)

In [41]:
a1.size

3

In [42]:
a2=np.ones([3,4])
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
a2=np.ones([3,4],dtype=int)
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
a2.ndim

2

In [45]:
a2.size

12

In [46]:
a2.shape

(3, 4)

In [47]:
a3=np.ones([4,2,3])
a3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [48]:
a3.shape

(4, 2, 3)

In [49]:
a3.size

24

In [50]:
import numpy as np
f1=np.full(3,9)
f1

array([9, 9, 9])

In [51]:
f2=np.full([2,3],9)
f2

array([[9, 9, 9],
       [9, 9, 9]])

In [52]:
f3=np.full([4,2,3],10)
f3

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])

In [53]:
f3=np.full([4,2,3],10,dtype='str')
f3

array([[['1', '1', '1'],
        ['1', '1', '1']],

       [['1', '1', '1'],
        ['1', '1', '1']],

       [['1', '1', '1'],
        ['1', '1', '1']],

       [['1', '1', '1'],
        ['1', '1', '1']]], dtype='<U1')

In [54]:
f3.ndim

3

In [55]:
f3.shape


(4, 2, 3)

In [56]:
f3.size

24

In [57]:
a=np.array([1,2,3])
b=np.array([1,2,3])
add=np.add(a,b)
add

array([2, 4, 6])

In [58]:
a=np.array([5,10,20])
b=np.array([4,8,10])
sub=np.subtract(a,b)
sub

array([ 1,  2, 10])

In [59]:
a=np.array([5,10,20])
b=np.array([4,8,10])
sub=np.multiply(a,b)
sub

array([ 20,  80, 200])

In [60]:
a=np.array([5,10,20])
b=np.array([4,8,10])
sub=np.divide(a,b)
sub

array([1.25, 1.25, 2.  ])

In [61]:
a=np.array([5,10,20])
b=np.array([4,8,10])
sub=np.mod(a,b)
sub

array([1, 2, 0])

In [62]:
a=np.array([5,10,20])
b=np.array([4,8,10])
sub=np.power(a,b)
sub

array([           625,      100000000, 10240000000000])